GET http://localhost:3000/health

###

GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/53928666-fb3d-4826-bf74-7f5ff5785613

###

POST http://localhost:3000/courses
Content-Type: application/json

{
  "name": "HTML 1",
  "provedor": "Alura",
  "category": "Programação Web",
  "duration": 8,
  "verifyUrl": "https://example.com"
}

###

PATCH http://localhost:3000/courses/53928666-fb3d-4826-bf74-7f5ff5785613
Content-Type: application/json

{
  "name": "Alterado via PATCH",
  "duration": 6,
  "verifyUrl": "https://cursos.alura.com.br/certificate/36b24b7a-48db-47ec-821d-895849a255bc"
}

###

DELETE http://localhost:3000/courses/53928666-fb3d-4826-bf74-7f5ff5785613