@rootUrl=http://localhost:3000

GET {{rootUrl}}/courses

###

GET {{rootUrl}}/courses/53928666-fb3d-4826-bf74-7f5ff5785613

###

POST {{rootUrl}}/courses
Content-Type: application/json

{
  "name": "HTML 1",
  "provedor": "Alura",
  "category": "Programação Web",
  "duration": 8,
  "verifyUrl": "https://example.com"
}

###

POST {{rootUrl}}/courses
Content-Type: application/json

{
  "name": "HTML5 e CSS3 parte 1: crie uma página da Web",
  "provedor": "Alura",
  "category": "Programação Web",
  "duration": 6,
  "verifyUrl": "https://cursos.alura.com.br/certificate/36b24b7a-48db-47ec-821d-895849a255bc"
}

###

PATCH {{rootUrl}}/courses/53928666-fb3d-4826-bf74-7f5ff5785613
Content-Type: application/json

{
  "name": "Alterado via PATCH",
  "duration": 6,
  "verifyUrl": "https://cursos.alura.com.br/certificate/36b24b7a-48db-47ec-821d-895849a255bc"
}

###

PATCH {{rootUrl}}/courses/53928666-fb3d-4826-bf74-7f5ff5785613
Content-Type: application/json

{
  "id": "53928666-fb3d-4826-bf74-7f5ff5785613",
  "name": "HTML5 e CSS3 parte 1: crie uma página da Web",
  "provedor": "Alura",
  "category": "Programação Web",
  "duration": 6,
  "verifyUrl": "https://cursos.alura.com.br/certificate/36b24b7a-48db-47ec-821d-895849a255bc"
}

###

DELETE {{rootUrl}}/courses/53928666-fb3d-4826-bf74-7f5ff5785613