@rootUrl=http://localhost:3000
@uuid=a5a582a4-3832-4d12-b779-2ea20540fa6c

GET {{rootUrl}}/volunteers

###

POST {{rootUrl}}/volunteers
Content-Type: application/json

{
    "occupation": "Lead and cofounder",
    "organization": "Makerspace",
    "startDate": "2021-01-01T00:00:00+00:00",
    "endDate": "2021-12-31T00:00:00+00:00",
    "category": "Engineering",
    "whatIDid": "Choose and trained 20 volunteers to work on 3d printing, marcenary and electronics projects",
    "whatILearned": "Leadership and project management"
}

###

POST {{rootUrl}}/volunteers
Content-Type: application/json

{
    "occupation": "Lead and cofounder",
    "organization": "Ex Machina",
    "startDate": "2021-01-01T00:00:00+00:00",
    "endDate": "2021-12-31T00:00:00+00:00",
    "category": "Engineering",
    "whatIDid": "Raised 20k to create the project",
    "whatILearned": "Leadership and project management"
}

###

GET {{rootUrl}}/volunteers/{{uuid}}

###

PATCH {{rootUrl}}/volunteers/{{uuid}}
Content-Type: application/json

{
    "occupation": "Patched"
}