@rootUrl=http://localhost:3000

###

GET {{rootUrl}}/works

###

GET {{rootUrl}}/works/909704e5-4003-40bd-87e3-ce23180877eb

###

POST {{rootUrl}}/works
Content-Type: application/json

{
    "name": "name",
    "occupation": "occupation",
    "startDate": "2020-06-01T00:00:00+00:00",
    "endDate": "2021-12-01T00:00:00+00:00",
    "description": "description",
    "category": "other"
}

###

POST {{rootUrl}}/works
Content-Type: application/json

{
    "name": "EndDate as optional",
    "occupation": "EndDate",
    "startDate": "2022-06-01T00:00:00+00:00",
    "description": "EndDate",
    "category": "other"
}

###

POST {{rootUrl}}/works
Content-Type: application/json

{
    "name": "Statement as optional",
    "occupation": "Statement",
    "startDate": "2022-06-01T00:00:00+00:00",
    "endDate": "2024-01-01T00:00:00+00:00",
    "description": "Statement",
    "category": "other",
    "statement": "Statement"
}

###

PATCH {{rootUrl}}/works/909704e5-4003-40bd-87e3-ce23180877eb
Content-Type: application/json

{
    "name": "PATCH updated",
    "occupation": "Patch",
    "startDate": "2016-06-01T00:00:00+00:00",
    "endDate": "2017-01-01T00:00:00+00:00",
    "description": "Patch",
    "category": "edited",
    "statement": "Patch"
}

###

DELETE {{rootUrl}}/works/909704e5-4003-40bd-87e3-ce23180877eb