@rootUrl=http://localhost:3000
@uuid=41d8181d-91c8-4dc9-954d-514891a24360

GET {{rootUrl}}/educations

###

GET {{rootUrl}}/educations/{{uuid}}

###

POST {{rootUrl}}/educations
Content-Type: application/json

{
    "title": "Education 1",
    "institution": "University 1",
    "startDate": "2009-09-01T00:00:00+00:00",
    "endDate": "2010-06-01T00:00:00+00:00",
    "location": "Local",
    "duration": 1000,
    "verifyUrl": "http://verify.com/education/1"
}

###

POST {{rootUrl}}/educations
Content-Type: application/json

{
    "title": "BSc Computer Science",
    "institution": "University of Lagos",
    "startDate": "2015-09-01T00:00:00+00:00",
    "endDate": "2020-06-01T00:00:00+00:00",
    "location": "Lagos, Nigeria",
    "duration": 4600,
    "verifyUrl": "http://verify.com/education/1"
}

###

POST {{rootUrl}}/educations
Content-Type: application/json

{
    "title": "Date Error",
    "institution": "University of Lagos",
    "startDate": "2015-09-01T00:00:00+00:00",
    "endDate": "2010-06-01T00:00:00+00:00",
    "location": "Lagos, Nigeria",
    "duration": 4600,
    "verifyUrl": "http://verify.com/education/1"
}

###

PATCH {{rootUrl}}/educations/{{uuid}}
Content-Type: application/json

{
    "title": "PATCH Computer Science",
    "startDate": "2008-09-01T00:00:00+00:00",
    "endDate": "2009-06-01T00:00:00+00:00",
    "duration": 2300,
    "verifyUrl": "http://verify.com/patch"
}

###

PATCH {{rootUrl}}/educations/{{uuid}}
Content-Type: application/json

{
    "title": "BSc Computer Science",
    "institution": "University of Lagos",
    "startDate": "2015-09-01T00:00:00+00:00",
    "endDate": "2020-06-01T00:00:00+00:00",
    "location": "Lagos, Nigeria",
    "duration": 4600,
    "verifyUrl": "http://verify.com/education/1"
}

###

DELETE {{rootUrl}}/educations/{{uuid}}